version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: mi-postgres-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=miappdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_local:
    driver: local 