version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mi-arquetipo-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: mi-arquetipo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend 