# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - front-paquetes-turisticos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://paqueteturisiticoscontainer.azurecr.io/
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        
    - name: Set lowercase username
      id: lowercase
      run: echo "registry_username=$(echo ${{ secrets.AZURE_REGISTRY_USERNAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: paqueteturisiticoscontainer.azurecr.io/${{ steps.lowercase.outputs.registry_username }}/santiprimerproyecto:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Set lowercase username
      id: lowercase
      run: echo "registry_username=$(echo ${{ secrets.AZURE_REGISTRY_USERNAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'front-paquetes-turisticos'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6d8c2ab063134ef79002b193fc922695 }}
        images: 'paqueteturisiticoscontainer.azurecr.io/${{ steps.lowercase.outputs.registry_username }}/santiprimerproyecto:${{ github.sha }}'